# ---------------- #
#   Main Configs   #
# ---------------- #
title: 搜云库
author: 鹏磊
subtitle: "Talk is cheap. Show me the code."
description: "搜云库"
baseurl:
url: http://www.souyunku.com
date_format: "ordinal"
keywords: 搜云库、内容涵盖 Spring Boot、Spring Cloud、微服务架构、大数据，云计算，运维开发、系统监控等相关的研究与知识分享
favicon: /favicon.ico
#timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author:  Peng Lei
organization: souyunku.com
organization_url: http://souyunku.com
github_username: souyunku
location: beijing, China
email: admin@souyunku.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基
    
  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: souyunku/souyunku.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: souyunku
# https://gentie.163.com
#netease_gentie:
   # productKey: 560ed243b708465d82d5a0a5f3b83da1
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: souyunku
  repo: blog-comments
  oauth:
      client_id: 6dfcd9b6a50c0f2ca145
      client_secret: d255736449b0fb7004e50080f18bf4a5c9a082f2
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
 #   analytics_id: 
